name: Lint
on:
  pull_request:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.2.0"
          cache: "npm"

      - name: Install npm@9.6.5
        run: npm i -g npm@9.6.5

      - name: Install dependencies
        id: install-dependencies
        run: npm ci --prefer-offline

      - name: Typecheck
        run: npm run typecheck

      - name: Lint
        if: (success() || failure()) && steps.install-dependencies.outcome == 'success'
        run: npm run lint

      - name: Format
        if: (success() || failure()) && steps.install-dependencies.outcome == 'success'
        run: npm run format
